In [195]:
#example data set
#we have the data set with two class
#data set has the 10 elament 4 elemnet A class and 6 element B class
n_A=4
n_B=6
total=n_A+n_B

#calculate the proportion
p_A=n_A/total
p_B=n_B/total

print(p_A)
print(p_B)


0.4
0.6


In [196]:
#calculate the entropy
import math
entropy= -p_A * math.log2(p_A) -p_B * math.log2(p_B)
print(f"Entropy = {entropy:.2f}")

Entropy = 0.97


In [197]:
 #gini impurity
gini=1 - p_A **2 - p_B**2
print(f"Gini impurity :{gini:0.2f}")

Gini impurity :0.48


# Deciion Tree   
**You  perform EDA ,data preprocessing on this dataset**  
**In previous titanic dataset I perform**

In [198]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [199]:
#load the data set
titanic=sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [200]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [201]:
#Drop the deck coloumn
titanic.drop("deck",axis=1,inplace =True)

#Impute the missimg values
imputer=SimpleImputer(strategy="median")
titanic[['age']]=imputer.fit_transform(titanic[['age']])

#impute the categorical data
imputer=SimpleImputer(strategy="most_frequent")
titanic[['embarked','embark_town']]=imputer.fit_transform(titanic[['embarked','embark_town']])



In [202]:
#Encode the data
le=LabelEncoder()
for i in titanic.select_dtypes(include=['category','object']):
    titanic[i]=le.fit_transform(titanic[i])

#other method
"""for col in titanic.columns:
    if titanic[col].dtype =='object' or titanic[col].dtype=='category':
        titanic[col]=LabelEncoder().fit_transform(titanic[col])"""

titanic.head()

survived  pclass  sex   age  sibsp  parch     fare  embarked  class  who  \
0         0       3    1  22.0      1      0   7.2500         2      2    1   
1         1       1    0  38.0      1      0  71.2833         0      0    2   
2         1       3    0  26.0      0      0   7.9250         2      2    2   
3         1       1    0  35.0      1      0  53.1000         2      0    2   
4         0       3    1  35.0      0      0   8.0500         2      2    1   

   adult_male  embark_town  alive  alone  
0        True            2      0  False  
1       False            0      1  False  
2       False            2      1   True  
3       False            2      1  False  
4        True            2      0   True

In [203]:
#train test and split the data

X=titanic.drop('survived',axis=1)
Y=titanic["survived"]

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

#Build the model
model=DecisionTreeClassifier()

model.fit(X_train,Y_train)

#Predict the model
Y_pred=model.predict(X_test)

#Evaluate the model
print("Accuracy score = ",accuracy_score(Y_test, Y_pred))
print("classification matrix  \n",classification_report(Y_test,Y_pred))
print('Confusion matrix \n',confusion_matrix(Y_test,Y_pred))

Accuracy score =  1.0
classification matrix  
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00        74

    accuracy                           1.00       179
   macro avg       1.00      1.00      1.00       179
weighted avg       1.00      1.00      1.00       179

Confusion matrix 
 [[105   0]
 [  0  74]]


In [204]:
#Remove the warning 
import warnings
warnings.filterwarnings("ignore")
model.predict([[3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False]])



array([0], dtype=int64)

In [205]:
model.predict([[1,	0,	19.0,	0,	0,	30.00,	2,	0,	2,	False,	2,	1,	True]])

array([1], dtype=int64)

**0 --> not survive**  
**1 --> survived**

In [181]:
titanic.tail()

survived  pclass  sex   age  sibsp  parch   fare  embarked  class  who  \
886         0       2    1  27.0      0      0  13.00         2      1    1   
887         1       1    0  19.0      0      0  30.00         2      0    2   
888         0       3    0  28.0      1      2  23.45         2      2    2   
889         1       1    1  26.0      0      0  30.00         0      0    1   
890         0       3    1  32.0      0      0   7.75         1      2    1   

     adult_male  embark_town  alive  alone  
886        True            2      0   True  
887       False            2      1   True  
888       False            2      0  False  
889        True            0      1   True  
890        True            1      0   True