In [23]:
import numpy as np # type: ignore
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report 
from sklearn.datasets import load_iris



In [24]:
df=load_iris()
#feature and target variable
X=df.data

Y=df.target
#Train test and split the data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [25]:
#Gaussian model
#Build the model
model=GaussianNB()

#Train the model
model.fit(X_train,Y_train)
#predication
Y_pred=model.predict(X_test)

#Evaluate the model
print("accuracy_score ",accuracy_score(Y_test,Y_pred))
print("confusion_matrix = \n",confusion_matrix(Y_test,Y_pred))
print("classification report \n= ",classification_report(Y_test,Y_pred))

accuracy_score  1.0
confusion_matrix = 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
classification report 
=                precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [26]:
#Multinomial NB
#Build the model
mnb=MultinomialNB()

#Train the model
mnb.fit(X_train,Y_train)
#predication
Y_pred=mnb.predict(X_test)

#Evaluate the model
print("accuracy_score ",accuracy_score(Y_test,Y_pred))
print("confusion_matrix = \n",confusion_matrix(Y_test,Y_pred))
print("classification report \n= ",classification_report(Y_test,Y_pred))

accuracy_score  0.9
confusion_matrix = 
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
classification report 
=                precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



In [27]:
#Burali NB
#Build the model
bnb=BernoulliNB()

#Train the model
bnb.fit(X_train,Y_train)
#predication
Y_pred=mnb.predict(X_test)

#Evaluate the model
print("accuracy_score ",accuracy_score(Y_test,Y_pred))
print("confusion_matrix = \n",confusion_matrix(Y_test,Y_pred))
print("classification report \n= ",classification_report(Y_test,Y_pred))

accuracy_score  0.9
confusion_matrix = 
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
classification report 
=                precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30

